version: '3'

services:
  redis:
    image: redis:4.0
    container_name: hipster-robot-redis
    volumes:
      - ./docker/data/redis:/data
    ports:
      - "6379:6379"
  dev:
    build: .
    container_name: hipster-robot-dev
    command: node_modules/.bin/gulp
    volumes:
     - .:/usr/src/app
    depends_on:
      - redis
    env_file: .env
    ports:
      - "4000:4000"
